language: node_js
node_js:
  - '6'
  - '5'
  - '4'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jslib' ]; then cd .. && eval "mv $currentfolder generator-jslib" && cd generator-jslib; fi
